const express = require("express"); //allows use of express as a dependency

const ejs = require("ejs"); //allows the use of ejs as a dependency

const bodyParser = require("body-Parser"); //allows use of body-Parser as a dependency

const mongoose = require("mongoose"); //allows use of mongoose as a dependency

const app = express(); 

app.use(bodyParser.urlencoded({extended:true}));//use body-Parser to grab stuff from the client


app.set("view engine", "ejs"); //use our app that is generated by ejs as its view engine

mongoose.connect("mongodb:localhost:27017/wikiDB", {useNewUrlParser:true}); //helps to use mongoose to connect to our database

//set up document schema for the db
const articleSchema = {
    title: String,
    content: String
}

const Article = mongoose.model("Article", articleSchema) //use the class to construct a document.