const express = require("express"); //allows use of express s a dependency fom the modules

const ejs = require("ejs"); //allows the use of ejs s a dependency fom the modules

const bodyParser = require("body-Parser"); //allows use of body-Parser as a dependency fom the modules

const mongoose = require("mongoose"); //allows use of mongoose as a dependency fom the modules

const app = express(); 

app.use(bodyParser.urlencoded({extended:true}));//use body-Parser to grab stuff from the client

//this helps us use express to serve up static files to the browser like CSS for this case
app.use(express.static("public"));


app.set("view engine", "ejs"); //use our app that is generated by ejs as its view engine

mongoose.connect("mongodb://localhost:27017/wikiDB", {useNewUrlParser:true}); //helps to use mongoose to connect to our database & property is added for errors

//set up document schema for the db
const articleSchema = {
    title: String,
    content: String
}

const Article = mongoose.model("Article", articleSchema); //this creates the article model using mongoose


app.listen("3000",()=>{

    console.log("server is up and running!!!");

});